---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pslab
  labels: 
    app: api-pslab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-pslab
  template:
    metadata:
      labels:
        app: api-pslab
    spec:
      containers:
      - name: api-pslab
        image: gcr.io/caramel-compass-393820/pslab_api:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: pslab-cm
              key: DATABASE_URL
        ports:
        - containerPort: 8000
