apiVersion: v1
kind: Service
metadata:
  name: frontend-pslab
spec:
  ports:
  - port: 80
    nodePort: 31001
    targetPort: 4200
    protocol: TCP
  selector:
    app: frontend-pslab
  type: LoadBalancer